UPDATE_NR_GROUPS		= 2
MAX_GROUP_UPDATE_COST		= 1.0
GROUP_UPDATE_COST_LOW		= 0.25
GROUP_UPDATE_COST_MEDIUM	= 0.5
GROUP_UPDATE_COST_HIGH		= 1.0
UPDATE_FREQUENCY		= 0.1

CLOSE_TO_LIMIT			= 12
POSITION_TEST_LIMIT		= 32
POSITION_TEST_STEP_SIZE		= 8
MAX_MOVE_ORDERS_PER_UPDATE	= 32

CMD_PRIMARY			= 0
CMD_ATTACK			= 1
CMD_BASE			= 2

COMBAT_DELAY			= 5.0

DEFAULT_FORMATION_DISTANCE	= 8.0
DEFAULT_COVER_DISTANCE_FORWARD	= 128.0

ATTACK_MODE_UPDATE_FREQUENCY	= 4.0
ATTACK_MODE_DISTANCE		= 192

FORMATION_BOX			= 1
FORMATION_LINE			= 2
FORMATION_COVER			= 3

SURROUND_NORMAL			= 0
SURROUND_OUT			= 1
SURROUND_IN			= 2

MAX_NUMBER_OF_UNITS		= 512
INVALID_UNIT_ID			= -1
NO_SQUAD_ID			= 0
MAX_SQUAD_SIZE			= 6
MAX_GROUP_SIZE			= 256

PLATOON_DEFAULT_UPDATE_TIME	= 32.0

BHB_PATROL_NO_DELAY		= 0
BHB_PATROL_ENDPOINTS_DELAY	= 1
BHB_PATROL_ALLPOINTS_DELAY	= 2

BHB_PATROL_NORMAL	= 0
BHB_PATROL_CIRCULAR	= 1
BHB_PATROL_RANDOM	= 2
