import base


F1_MARINE = base.StringToInt("F1_Marine")
F1_MARINE_COPY_NO_SCORE = base.StringToInt("F1_Marine_Copy_NoScore" )
US_AA_INFANTRY = base.StringToInt("US_AA_Infantry")


US_SQUAD_INFANTRY = base.StringToInt("US_Squad_Infantry")
US_SQUAD_MECHANIZED = base.StringToInt("US_Squad_Mechanized")
US_SQUAD_AIRBORNE = base.StringToInt("US_Squad_Airborne")

US_MACHINE_GUNNER = base.StringToInt("US_Machine_Gunner")
US_MEDIC = base.StringToInt("US_Medic")
US_ANTITANK = base.StringToInt("US_AntiTank")
US_ENGINEER = base.StringToInt("US_Engineer")
US_SNIPER = base.StringToInt("US_Sniper")
US_MEDIC_W_SPECIAL = base.StringToInt("US_Medic_w_Special")
US_M1_ABRAMS = base.StringToInt("US_Tank_Abrahms") ##reverted
US_M60A3 = base.StringToInt("US_M60A3")
US_SHERIDAN = base.StringToInt("US_Sheridan")
US_BRADLEY_APC = base.StringToInt("US_Bradley_APC")
US_AAVP7A1 = base.StringToInt("US_AAVP7A1")
US_M270 = base.StringToInt("US_M270")
US_M88A1_ARV = base.StringToInt("US_M88A1_Arv")
US_M730A2_AA = base.StringToInt("US_M730A2_AA")
US_M125_MORTAR = base.StringToInt("US_M125_Mortar")
US_HUMVEE = base.StringToInt("US_HUMWEE") ##reverted
US_AH_APACHE = base.StringToInt("US_AH_Apache")
US_AH1_SUPER_COBRA = base.StringToInt("US_AH1_Super_Cobra")
US_BLACKHAWK_UH = base.StringToInt("US_Blackhawk_UH")
US_OH_6A_CAYUSE = base.StringToInt("US_OH_6A_Cayuse")
US_TRUCK = base.StringToInt( "US_M-939_Truck" ) 
US_M163 = base.StringToInt( "US_M163" )

US_HUMWEE_FAST = base.StringToInt( "US_HUMWEE_FAST" )
US_TANK_ACE = base.StringToInt( "US_Tank_Ace_Immobile" )
US_AA_LESSDAMAGE = base.StringToInt( "US_M730A2_AA_LessDamage" )

NATO_SQUAD_INFANTRY = base.StringToInt("NATO_Squad_Infantry")
NATO_SQUAD_MECHANIZED = base.StringToInt("NATO_Squad_Mechanized")
NATO_SQUAD_AIRBORNE = base.StringToInt("NATO_Squad_Airborne")

NATO_MARINE = base.StringToInt("NATO_Marine")
NATO_MARINE_COPY_NO_SCORE = base.StringToInt("NATO_Marine_Copy_NoScore" )
NATO_MACHINE_GUNNER = base.StringToInt("NATO_Machine_Gunner")
NATO_MEDIC = base.StringToInt("NATO_Medic")
NATO_ANTITANK = base.StringToInt("NATO_AntiTank")
NATO_ENGINEER = base.StringToInt("NATO_Engineer")
NATO_SNIPER = base.StringToInt("NATO_Sniper")
NATO_AA_INFANTRY = base.StringToInt("NATO_AA_Infantry")
NATO_MEDIC_W_SPECIAL = base.StringToInt("NATO_Medic_w_Special")
NATO_LEOPARD2 = base.StringToInt("NATO_Tank_Leopard2") ##reverted
NATO_CHIEFTAIN_MKV = base.StringToInt("NATO_Chieftain_MkV")
NATO_FV101_SCORPION = base.StringToInt("NATO_AMX30") ##reverted
NATO_WARRIOR_APC = base.StringToInt("NATO_Warrior_APC")
NATO_RECON_LUCHS = base.StringToInt("NATO_Recon_Luchs")
NATO_LARS_SF_2 = base.StringToInt("NATO_LARS_SF_2")
NATO_CHIEFTAIN_AAVR_CHAARV = base.StringToInt("NATO_Chieftain_AAVR_CHAARV")
NATO_GEPARD_AA = base.StringToInt("NATO_Gepard_AA")
NATO_MORTAR_WEASEL = base.StringToInt("NATO_Mortar_Weasel")
NATO_LANDROVER = base.StringToInt("NATO_LandRover")
NATO_MANGUSTA = base.StringToInt("NATO_Mangusta")
NATO_GAZELLE_341 = base.StringToInt("NATO_Gazelle_341")
NATO_SUPERPUMA_UH = base.StringToInt("NATO_Superpuma_UH")
NATO_PAH_1_BO105 = base.StringToInt("NATO_PAH_1_Bo105")
NATO_TRUCK = base.StringToInt( "NATO_Renault_4000" )
NATO_SCORPION = base.StringToInt( "NATO_FV101_Scorpion" )
NATO_ROLAND = base.StringToInt( "NATO_Marder_Roland" )

NATO_AA_LESSDAMAGE = base.StringToInt( "NATO_Marder_Roland_LessDamage" )

USSR_SQUAD_INFANTRY = base.StringToInt("USSR_Squad_Infantry")
USSR_SQUAD_MECHANIZED = base.StringToInt("USSR_Squad_Mechanized")
USSR_SQUAD_AIRBORNE = base.StringToInt("USSR_Squad_Airborne")

USSR_MARINE = base.StringToInt("USSR_Marine")
USSR_MARINE_COPY_NO_SCORE = base.StringToInt("USSR_Marine_Copy_NoScore" )
USSR_MACHINE_GUNNER = base.StringToInt("USSR_Machine_Gunner")
USSR_MEDIC = base.StringToInt("USSR_Medic")
USSR_ANTITANK = base.StringToInt("USSR_AntiTank")
USSR_AA_INFANTRY = base.StringToInt("USSR_AA_Infantry")
USSR_ENGINEER = base.StringToInt("USSR_Engineer")
USSR_SNIPER = base.StringToInt("USSR_Sniper")
USSR_MEDIC_W_SPECIAL = base.StringToInt("USSR_Medic_w_Special") # part of the single player infantry squad (080725 HA)
USSR_T80U = base.StringToInt("USSR_T80U")
USSR_T62 = base.StringToInt("USSR_T62")
USSR_PT_76 = base.StringToInt("USSR_Bmp_R") ##reverted
USSR_BMP_2 = base.StringToInt("USSR_Bmp_3") ##reverted
USSR_BTR80 = base.StringToInt("USSR_Btr80")
USSR_2S7_PION = base.StringToInt("USSR_2S7_Pion")
USSR_VT55 = base.StringToInt("USSR_VT55")
USSR_ZSU_SHILKA = base.StringToInt("USSR_ZSU_Shilka")
USSR_2S9_ANONA = base.StringToInt("USSR_2S9_Anona")
USSR_UAZ469 = base.StringToInt("USSR_UAZ469")
USSR_AH_MI24 = base.StringToInt("USSR_AH_MI24")
USSR_MI28_HAVOC = base.StringToInt("USSR_Mi28_Havoc")
USSR_MI8_HIP = base.StringToInt("USSR_Mi8_Hip")
USSR_KA_25_HORMONE = base.StringToInt("USSR_Ka-25_Hormone")
USSR_TRUCK = base.StringToInt( "USSR_Ural_4320" )
USSR_VIPCAR = base.StringToInt( "VIPCar" ) 
USSR_GOPHER = base.StringToInt( "USSR_SA13_Gopher" )
USSR_STYX = base.StringToInt("SP_USSR_4K51_Rubezh")

USSR_RUSSIA3_SPECIAL_PION = base.StringToInt("USSR_RUSSIA3_SPECIAL_2S7_Pion")

USSR_SQUAD_INFANTRY_RB = base.StringToInt("USSR_REBALANCED_Squad_Infantry")
USSR_SQUAD_MECHANIZED_RB = base.StringToInt("USSR_REBALANCED_Squad_Mechanized")
USSR_SQUAD_AIRBORNE_RB = base.StringToInt("USSR_REBALANCED_Squad_Airborne")

USSR_MARINE_RB = base.StringToInt("USSR_REBALANCED_Marine")
USSR_MARINE_COPY_NO_SCORE_RB = base.StringToInt("USSR_REBALANCED_Marine_Copy_NoScore" )
USSR_MACHINE_GUNNER_RB = base.StringToInt("USSR_REBALANCED_Machine_Gunner")
USSR_MEDIC_RB = base.StringToInt("USSR_REBALANCED_Medic")
USSR_ANTITANK_RB = base.StringToInt("USSR_REBALANCED_AntiTank")
USSR_AA_INFANTRY_RB = base.StringToInt("USSR_REBALANCED_AA_Infantry")
USSR_ENGINEER_RB = base.StringToInt("USSR_REBALANCED_Engineer")
USSR_SNIPER_RB = base.StringToInt("USSR_REBALANCED_Sniper")
USSR_T80U_RB = base.StringToInt("USSR_REBALANCED_T80U")
USSR_T62_RB = base.StringToInt("USSR_REBALANCED_T62")
USSR_PT_76_RB = base.StringToInt("USSR_REBALANCED_Bmp_R") ##reverted
USSR_BMP_2_RB = base.StringToInt("USSR_REBALANCED_Bmp_3") ##reverted
USSR_BTR80_RB = base.StringToInt("USSR_REBALANCED_Btr80")
USSR_2S7_PION_RB = base.StringToInt("USSR_REBALANCED_2S7_Pion")
USSR_VT55_RB = base.StringToInt("USSR_REBALANCED_VT55")
USSR_ZSU_SHILKA_RB = base.StringToInt("USSR_REBALANCED_ZSU_Shilka")
USSR_2S9_ANONA_RB = base.StringToInt("USSR_REBALANCED_2S9_Anona")
USSR_UAZ469_RB = base.StringToInt("USSR_REBALANCED_UAZ469")
USSR_AH_MI24_RB = base.StringToInt("USSR_REBALANCED_AH_MI24")
USSR_MI28_HAVOC_RB = base.StringToInt("USSR_REBALANCED_Mi28_Havoc")
USSR_MI8_HIP_RB = base.StringToInt("USSR_REBALANCED_Mi8_Hip")
USSR_KA_25_HORMONE_RB = base.StringToInt("USSR_REBALANCED_Ka-25_Hormone")
USSR_TRUCK_RB = base.StringToInt( "USSR_REBALANCED_Ural_4320" )
USSR_VIPCAR_RB = base.StringToInt( "VIPCar" ) 
USSR_GOPHER_RB = base.StringToInt( "USSR_REBALANCED_SA13_Gopher" )
USSR_STYX_RB = base.StringToInt("SP_USSR_REBALANCED_4K51_Rubezh")


## temporary fixes for backward compability, don't use!!!
USSR_BMP_R = USSR_PT_76
USSR_BMP_3 = USSR_BMP_2
US_TANK_ABRAHMS = US_M1_ABRAMS
US_HUMWEE = US_HUMVEE
NATO_TANK_LEOPARD2 = NATO_LEOPARD2
NATO_AMX30 = NATO_FV101_SCORPION


NEUTRAL_SCHOOLBUS = base.StringToInt("Neutral_Schoolbus")


SP_Tutorial_OPFOR_Inf	= base.StringToInt("SP_Tutorial_OPFOR_Inf")
SP_Tutorial_OPFOR_Jeep	= base.StringToInt("SP_Tutorial_OPFOR_Jeep")

SP_Tutorial_US_MARINE_WALK = base.StringToInt( 'SP_US_Rifleman' ) 

SP_Tutorial_SU = base.StringToInt( 'SP_SU25_Frogfoot_Special' )

SP_US_HUMWEE_LIGHTS = base.StringToInt( 'SP_US_HUMWEE_LIGHTS' )

NATO_ANTITANK_NO_DAMAGE = base.StringToInt( 'NATO_AntiTank_No_Damage' ) 

# aliases

USSR_HIND = USSR_AH_MI24
USSR_JEEP = USSR_UAZ469
USSR_SCOUTCOPTER = USSR_KA_25_HORMONE
USSR_AMPHIBIOUS = USSR_BTR80

US_MARINE = F1_MARINE
US_ABRAHMS = US_TANK_ABRAHMS
US_AMPHIBIOUS = US_AAVP7A1
US_ANTIAIR = US_M730A2_AA
US_APACHE = US_AH_APACHE
US_SUPERCOBRA = US_AH1_SUPER_COBRA
US_BLACKHAWK = US_BLACKHAWK_UH
US_CAYUSE = US_OH_6A_CAYUSE


# Names by class      added 2007-10-02 MS

NATO_LIGHT_TANK = NATO_FV101_SCORPION
NATO_MEDIUM_TANK = NATO_CHIEFTAIN_MKV
NATO_HEAVY_TANK = NATO_LEOPARD2
NATO_REPAIR_TANK = NATO_CHIEFTAIN_AAVR_CHAARV
NATO_MEDIUM_AA = NATO_GEPARD_AA
NATO_HEAVY_AA = NATO_ROLAND
NATO_JEEP = NATO_LANDROVER
NATO_AMPHIBIOUS = NATO_RECON_LUCHS
NATO_TRANSPORT = NATO_WARRIOR_APC
NATO_MEDIUM_ART = NATO_MORTAR_WEASEL
NATO_HEAVY_ART = NATO_LARS_SF_2
NATO_SCOUT_COPTER = NATO_PAH_1_BO105
NATO_TRANSPORT_COPTER = NATO_SUPERPUMA_UH
NATO_MEDIUM_COPTER = NATO_GAZELLE_341
NATO_HEAVY_COPTER = NATO_MANGUSTA

USSR_LIGHT_TANK = USSR_PT_76
USSR_MEDIUM_TANK = USSR_T62
USSR_HEAVY_TANK = USSR_T80U
USSR_REPAIR_TANK = USSR_VT55
USSR_MEDIUM_AA = USSR_ZSU_SHILKA
USSR_HEAVY_AA = USSR_GOPHER
USSR_TRANSPORT = USSR_BMP_2
USSR_MEDIUM_ART = USSR_2S9_ANONA
USSR_HEAVY_ART = USSR_2S7_PION
USSR_SCOUT_COPTER = USSR_KA_25_HORMONE
USSR_TRANSPORT_COPTER = USSR_MI8_HIP
USSR_MEDIUM_COPTER = USSR_MI28_HAVOC
USSR_HEAVY_COPTER = USSR_AH_MI24

USSR_LIGHT_TANK_RB = USSR_PT_76_RB
USSR_MEDIUM_TANK_RB = USSR_T62_RB
USSR_HEAVY_TANK_RB = USSR_T80U_RB
USSR_REPAIR_TANK_RB = USSR_VT55_RB
USSR_MEDIUM_AA_RB = USSR_ZSU_SHILKA_RB
USSR_HEAVY_AA_RB = USSR_GOPHER_RB
USSR_TRANSPORT_RB = USSR_BMP_2_RB
USSR_MEDIUM_ART_RB = USSR_2S9_ANONA_RB
USSR_HEAVY_ART_RB = USSR_2S7_PION_RB
USSR_SCOUT_COPTER_RB = USSR_KA_25_HORMONE_RB
USSR_TRANSPORT_COPTER_RB = USSR_MI8_HIP_RB
USSR_MEDIUM_COPTER_RB = USSR_MI28_HAVOC_RB
USSR_HEAVY_COPTER_RB = USSR_AH_MI24_RB
USSR_JEEP_RB = USSR_UAZ469_RB

US_LIGHT_TANK = US_SHERIDAN
US_MEDIUM_TANK = US_M60A3
US_HEAVY_TANK = US_M1_ABRAMS
US_REPAIR_TANK = US_M88A1_ARV
US_MEDIUM_AA = US_M163
US_HEAVY_AA = US_M730A2_AA
US_JEEP = US_HUMVEE
US_TRANSPORT = US_BRADLEY_APC
US_MEDIUM_ART = US_M125_MORTAR
US_HEAVY_ART = US_M270
US_SCOUT_COPTER = US_OH_6A_CAYUSE
US_TRANSPORT_COPTER = US_BLACKHAWK_UH
US_MEDIUM_COPTER = US_AH1_SUPER_COBRA
US_HEAVY_COPTER = US_AH_APACHE


# unitTypeLists

unitTypeList_US_SquadInfantry = [ US_MARINE, US_MARINE, US_AA_INFANTRY, US_MACHINE_GUNNER, US_ANTITANK, US_MEDIC ]
unitTypeList_US_SquadMechanized = [ US_ANTITANK, F1_MARINE, US_ANTITANK, US_MEDIC, US_ANTITANK ]
unitTypeList_US_SquadSniper = [ US_SNIPER, US_SNIPER, US_SNIPER, US_SNIPER ]

unitTypeList_USSR_SquadInfantry = [ USSR_MARINE, USSR_MARINE, USSR_AA_INFANTRY, USSR_MACHINE_GUNNER, USSR_ANTITANK, USSR_MEDIC ]
unitTypeList_USSR_SquadMechanized = [ USSR_ANTITANK, USSR_MARINE, USSR_ANTITANK, USSR_MARINE, USSR_MEDIC, USSR_ANTITANK ]
unitTypeList_USSR_SquadSniper =  [ USSR_SNIPER, USSR_SNIPER ]

unitTypeList_USSR_SquadInfantry_RB = [ USSR_MARINE_RB, USSR_MARINE_RB, USSR_AA_INFANTRY_RB, USSR_MACHINE_GUNNER_RB, USSR_ANTITANK_RB, USSR_MEDIC_RB ]
unitTypeList_USSR_SquadMechanized_RB = [ USSR_ANTITANK_RB, USSR_MARINE_RB, USSR_MARINE_RB, USSR_ANTITANK_RB, USSR_MEDIC_RB, USSR_ANTITANK_RB ]
unitTypeList_USSR_SquadSniper_RB =  [ USSR_SNIPER_RB, USSR_SNIPER_RB ]
 
unitTypeList_NATO_SquadMechanized = [ NATO_ANTITANK, NATO_ANTITANK, NATO_MEDIC, NATO_MARINE, NATO_ANTITANK ]


#UnitClassLists

squadUS = [US_SQUAD_INFANTRY, US_SQUAD_MECHANIZED, US_SQUAD_AIRBORNE]
squadNATO = [NATO_SQUAD_INFANTRY, NATO_SQUAD_MECHANIZED, NATO_SQUAD_AIRBORNE]
squadUSSR = [USSR_SQUAD_INFANTRY, USSR_SQUAD_MECHANIZED, USSR_SQUAD_AIRBORNE, USSR_SQUAD_AIRBORNE_RB, USSR_SQUAD_INFANTRY_RB, USSR_SQUAD_MECHANIZED_RB]

infantryUS = [F1_MARINE, US_MACHINE_GUNNER, US_MEDIC, US_ANTITANK, US_ENGINEER, US_SNIPER, US_AA_INFANTRY, F1_MARINE_COPY_NO_SCORE, SP_Tutorial_US_MARINE_WALK, US_SQUAD_INFANTRY, US_SQUAD_MECHANIZED, US_MEDIC_W_SPECIAL ]
infantryNATO = [NATO_MARINE, NATO_MACHINE_GUNNER, NATO_MEDIC, NATO_ANTITANK, NATO_ANTITANK_NO_DAMAGE, NATO_ENGINEER, NATO_SNIPER, NATO_AA_INFANTRY, NATO_MARINE_COPY_NO_SCORE, NATO_SQUAD_INFANTRY, NATO_SQUAD_MECHANIZED, NATO_MEDIC_W_SPECIAL ]
infantryUSSR = [USSR_MARINE, USSR_MACHINE_GUNNER, USSR_MEDIC, USSR_ANTITANK, USSR_ENGINEER, USSR_SNIPER, USSR_AA_INFANTRY, USSR_MARINE_COPY_NO_SCORE, USSR_MARINE_RB, USSR_MARINE_COPY_NO_SCORE_RB, USSR_MACHINE_GUNNER_RB, USSR_MEDIC_RB, USSR_ANTITANK_RB, USSR_AA_INFANTRY_RB, USSR_ENGINEER_RB, USSR_SNIPER_RB, USSR_SQUAD_INFANTRY, USSR_SQUAD_MECHANIZED, USSR_MEDIC_W_SPECIAL]

tanksUS = [US_TANK_ABRAHMS, US_M60A3, US_SHERIDAN ]
tanksNATO = [NATO_TANK_LEOPARD2, NATO_CHIEFTAIN_MKV, NATO_AMX30]
tanksUSSR = [USSR_T80U, USSR_T62, USSR_BMP_R, USSR_LIGHT_TANK_RB, USSR_MEDIUM_TANK_RB, USSR_HEAVY_TANK_RB ]

artilleryUS = [US_M270, US_M125_MORTAR]
artilleryNATO = [NATO_MORTAR_WEASEL, NATO_LARS_SF_2]
artilleryUSSR = [USSR_2S7_PION, USSR_2S9_ANONA, USSR_MEDIUM_ART_RB, USSR_MEDIUM_ART_RB ]

containerUS = [US_BRADLEY_APC, US_HUMWEE, US_BLACKHAWK_UH, US_AAVP7A1, US_TRUCK]
containerNATO = [NATO_WARRIOR_APC, NATO_RECON_LUCHS, NATO_SUPERPUMA_UH, NATO_TRUCK, NATO_LANDROVER]
containerUSSR = [USSR_UAZ469, USSR_BMP_3, USSR_MI8_HIP, USSR_BTR80, USSR_TRUCK, USSR_JEEP_RB, USSR_TRANSPORT_RB, USSR_TRANSPORT_COPTER_RB ]

airUS = [US_AH_APACHE, US_AH1_SUPER_COBRA, US_BLACKHAWK_UH, US_OH_6A_CAYUSE]
airNATO = [NATO_MANGUSTA, NATO_GAZELLE_341, NATO_SUPERPUMA_UH, NATO_PAH_1_BO105]
airUSSR = [USSR_AH_MI24, USSR_MI28_HAVOC, USSR_MI8_HIP, USSR_KA_25_HORMONE]

repairUS = [ US_M88A1_ARV, US_HUMWEE ]
repairNATO = [ NATO_CHIEFTAIN_AAVR_CHAARV, NATO_LANDROVER ]
repairUSSR = [ USSR_VT55, USSR_JEEP, USSR_REPAIR_TANK_RB, USSR_JEEP_RB ]


nullUnit = base.StringToInt("Null_Unit")
SpotterUnit = base.StringToInt("Spotter_Unit")



## default unit costs
unitCosts = {}

unitCosts["US_Squad_Infantry"] = 650
unitCosts["US_Squad_Mechanized"] = 800
unitCosts["US_Engineer"] = 900
unitCosts["US_Sniper"] = 500

unitCosts["NATO_Squad_Infantry"] = 650
unitCosts["NATO_Squad_Mechanized"] = 800
unitCosts["NATO_Engineer"] = 900
unitCosts["NATO_Sniper"] = 500

unitCosts["USSR_Squad_Infantry"] = 650
unitCosts["USSR_Squad_Mechanized"] = 800
unitCosts["USSR_Engineer"] = 900
unitCosts["USSR_Sniper"] = 500

unitCosts["USSR_REBALANCED_Squad_Infantry"] = 650
unitCosts["USSR_REBALANCED_Squad_Mechanized"] = 800
unitCosts["USSR_REBALANCED_Engineer"] = 900
unitCosts["USSR_REBALANCED_Sniper"] = 500

unitCosts["US_Tank_Abrahms"] = 1200 ##obsolete
unitCosts["US_M1_Abrams"] = 1200
unitCosts["US_M60A3"] = 800
unitCosts["US_Sheridan"] = 600
unitCosts["US_Bradley_APC"] = 750
unitCosts["US_AAVP7A1"] = 650
unitCosts["US_M270"] = 1900
unitCosts["US_M88A1_Arv"] = 900
unitCosts["US_M730A2_AA"] = 900
unitCosts["US_M125_Mortar"] = 900
unitCosts["US_HUMWEE"] = 550
unitCosts["US_AH_Apache"] = 1200
unitCosts["US_AH1_Super_Cobra"] = 900
unitCosts["US_Blackhawk_UH"] = 650
unitCosts["US_OH_6A_Cayuse"] = 600
unitCosts["US_M-939_Truck"] = 300  
unitCosts["US_M163"] = 650


unitCosts["NATO_Tank_Leopard2"] = 1200 ##obsolete
unitCosts["NATO_Leopard2"] = 1200
unitCosts["NATO_Chieftain_MkV"] = 800
unitCosts["NATO_FV101_Scorpion"] = 600
unitCosts["NATO_AMX30"] = 600 ##obsolete
unitCosts["NATO_FV101_Scorpion"] = 600
unitCosts["NATO_Warrior_APC"] = 750
unitCosts["NATO_Recon_Luchs"] = 650
unitCosts["NATO_LARS_SF_2"] = 1900
unitCosts["NATO_Chieftain_AAVR_CHAARV"] = 900
unitCosts["NATO_Gepard_AA"] = 650
unitCosts["NATO_Mortar_Weasel"] = 900
unitCosts["NATO_LandRover"] = 550
unitCosts["NATO_Mangusta"] = 1200
unitCosts["NATO_Gazelle_341"] = 900
unitCosts["NATO_Superpuma_UH"] = 650
unitCosts["NATO_PAH_1_Bo105"] = 600
unitCosts["NATO_Renault_4000"] = 300  
unitCosts["NATO_Marder_Roland"] = 300

unitCosts["USSR_T80U"] = 1200
unitCosts["USSR_T62"] = 800
unitCosts["USSR_Bmp_R"] = 600  ##obsolete
unitCosts["USSR_PT-76"] = 600
unitCosts["USSR_Bmp_3"] = 750 ##obsolete
unitCosts["USSR_Bmp_2"] = 750
unitCosts["USSR_Btr80"] = 650
unitCosts["USSR_2S7_Pion"] = 1900
unitCosts["USSR_VT55"] = 900
unitCosts["USSR_ZSU_Shilka"] = 650 
unitCosts["USSR_2S9_Anona"] = 1200
unitCosts["USSR_SA13_Gopher"] = 900
unitCosts["USSR_UAZ469"] = 500
unitCosts["USSR_AH_MI24"] = 1200
unitCosts["USSR_Mi28_Havoc"] = 900
unitCosts["USSR_Mi8_Hip"] = 650
unitCosts["USSR_Ka-25_Hormone"] = 600
unitCosts["USSR_Ural_4320"] = 300
unitCosts["VIPCar"] = 5000000

unitCosts["USSR_REBALANCED_T80U"] = 1200
unitCosts["USSR_REBALANCED_T62"] = 800
unitCosts["USSR_REBALANCED_Bmp_R"] = 600  ##obsolete
unitCosts["USSR_REBALANCED_PT-76"] = 600
unitCosts["USSR_REBALANCED_Bmp_3"] = 750 ##obsolete
unitCosts["USSR_REBALANCED_Bmp_2"] = 750
unitCosts["USSR_REBALANCED_Btr80"] = 650
unitCosts["USSR_REBALANCED_2S7_Pion"] = 1900
unitCosts["USSR_REBALANCED_VT55"] = 900
unitCosts["USSR_REBALANCED_ZSU_Shilka"] = 650 
unitCosts["USSR_REBALANCED_2S9_Anona"] = 1200
unitCosts["USSR_REBALANCED_SA13_Gopher"] = 900
unitCosts["USSR_REBALANCED_UAZ469"] = 500
unitCosts["USSR_REBALANCED_AH_MI24"] = 1200
unitCosts["USSR_REBALANCED_Mi28_Havoc"] = 900
unitCosts["USSR_REBALANCED_Mi8_Hip"] = 650
unitCosts["USSR_REBALANCED_Ka-25_Hormone"] = 600
unitCosts["USSR_REBALANCED_Ural_4320"] = 300
unitCosts["VIPCar"] = 5000000


